; Listing generated by Microsoft (R) Optimizing Compiler Version 19.11.25508.2 

; Generated by VC++ for Common Language Runtime
.file "C:\Users\yagiz\AppData\Local\Temp\.NETFramework,Version=v4.0.AssemblyAttributes.cpp"
